### ISSUE TITLE
[Bug] : Override Warning flags

### ISSUE THREAD

**Issue by carsanbu** [bebenlebricolo/CMakeAS7#42]
First at all, I am very grateful to this project, thank you @bebenlebricolo!
I am using the cmake with this [toolchain](https://github.com/bebenlebricolo/LabBenchPowerSupply/blob/master/Firmware/Toolchain/avr8-gcc-toolchain.cmake).
I want to suppress some warnings that are treated as errors, this is my CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.0)

set(MCU   atmega1284)

set(CMCU      "-mmcu=${MCU}")
set(CSTANDARD "-std=gnu99")

set(CMAKE_TOOLCHAIN_FILE ../../../toolchain/avr8-gcc-toolchain.cmake)
set(CFLAGS   "${CMCU} ${CSTANDARD} -Wno-unused-parameter -Wno-error=unused-function -Wno-error=unused-variable ")
set(CXXFLAGS "${CMCU} -Wno-unused-parameter -Wno-error=unused-function -Wno-error=unused-variable ")

set(CMAKE_C_FLAGS   "${CFLAGS}")
set(CMAKE_CXX_FLAGS "${CXXFLAGS}")
set(CMAKE_ASM_FLAGS   "${CFLAGS}")

# Project setup
...
```
The problem is the warning are not passed on to the atmel studio project and the build ever break with unused parameters.

**Comment by bebenlebricolo** [comment]
Hi @carsanbu and thank you for your feedback.
The first thing that comes to mind (to me) is that you can at least locally explicitely tell the compiler you don't want to use variables like so :
```c
void my_function(int a, int b, int c)
{
   (void) a;
   (void) b;
   (void) c;
   // more code
}
```
Casting a variable to void is essentially seen as a no-op by the compiler and is ignored at the execution (no instructions are generated in assembly and machine code). 
![image](https://user-images.githubusercontent.com/29211687/142399601-cb8a5a0d-b356-4110-a928-f703a0278bda.png)
[You can check for the example depicted here](https://godbolt.org/z/vY69GKqe7)

## Back to the question
In case you really want to use those flags directly within the CMakeLists.txt, I've done several things in order to support warnings but warnings with special value like -Wno-error=<payload> might not be parsed as expected. 
I tried to implement as much things I could for the flags but in the initial concept, parsed flags are not meant to embed the "=" assignment.

Normally, flags that are unknown to AtmelStudio should be listed under the "other flags" node, but I need to check if that stands true, there might be a hole in the implementation regarding this aspect (!).
I'll keep you posted when I have some time to spend on this !

**Comment by bebenlebricolo** [comment]
Starting some developments on it to fix this behavior.
This was caused by the extra warning flags not being deduced (I forgot some instructions in the codebase).

**Comment by bebenlebricolo** [comment]
Hi @carsanbu , I've implemented some fixes for this issue and I have some build artifacts that you may use for testing purposes.
Could you check with the [build located within this run](https://github.com/bebenlebricolo/CMake-AtmelStudio7-compatibility/actions/runs/1512598097) ?
You can go to the bottom of the page, and download the CMakeAS7-BuildArtifacts-winx64. It's basically the locally package version of cmake and as cmake is monolithic, you should be able to use it from the decompressed .zip archive.

You can also have a look at the PR itself, the changes were ported in the testing section. 

If your manual testing validates the build, I'll merge the PR and close the ticket ; then I'll repackage the whole thing and reupload the new files as latest artifacts.

**Comment by bebenlebricolo** [comment]
Hi  @carsanbu , your problem is now fixed and integrated into master branch. You can grab the [latest release 3.20.2-bugfix1](https://github.com/bebenlebricolo/CMakeAS7/releases/tag/3.20.2-bugfix1) and try it for yourself.
I've implemented a basic test project that mimics the kinds of inputs you might have in your project, more details can be found here : [AVR8_C_fake_app)](https://github.com/bebenlebricolo/CMakeAS7-TestProjects/tree/main/AVR8_C_fake_app).

It is handled correctly on my system and flags are parsed correctly ; unknown flags such as the ones you used are reported as "miscellaneous warning flags".

For now, this is the only integration test I'm running and it's very manual, I'm planning on adding the CMakeAS7-TestProjects repo as a submodule in order to automatically trigger them within the CI/CD pipelines.
I also updated the few tests I have at hands for now that check that sort of things : [testCmAvrGccCompiler.cpp](https://github.com/bebenlebricolo/CMakeAS7/blob/master/Tests/CMakeLib/testCmAtmelStudioTools/testCmAvrGccCompiler.cpp#L277).

Thanks for reporting this issue 👍
